apiVersion: v1
kind: PersistentVolume
metadata:
  name: usermysql-pv
spec:
  capacity: 
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/usermysql
